### ISSUE TITLE
Total Energie in kWh

### ISSUE THREAD

**Issue by hubtub2** [Tidone/homeassistant_eta_integration#6]
Hello, 

some time ago I wrote the original ETA integration that was now forked the second time, great work!
I am still using nigl's fork, but I will try to switch to your fork to have the writable sensors (to add a hot water request button).

I am using this template sensor to convert the total pellet consumption 
`<object uri="/40/10021/0/0/12016" name="Gesamtverbrauch"/>`
into unit kWh using a factor of 4.8.

This way it can be simply used in the energy panel as "Gas" heater (which only takes entities of unit kWh).

```
# Convert pellet consumption (kg) to energy consumption (kWh)
template:
  - sensor:
    - name: eta_gesamtenergie
      unique_id: '0a7576cc-d6c1-30ba-1ae1-611518c3497f'
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing 
      state: >
        {{ states('sensor.eta_kessel_zahlerstande_gesamtverbrauch') | float(default=0.0) | multiply(4.8) | round(1) }}

```
The original ETA integration simply added a "total energy" entitiy. 
Would this be a feature for your fork?
